### PR TITLE
ci: fix clippy actions workflow and add cargo-fmt action

### PR DESCRIPTION
**Pull request by dhilipsiva**
Clippy was already being used. But it never reported any problems. The errors were always suppressed because we were piping the clippy output to cargo-sarif. This piping masked the exit code of clippy command. Which is why you might notice clippy is run twice now.

Note: actions-rs was deprecated and archived because GH Actions now support for rust by default: https://github.com/actions/starter-workflows/blob/main/ci/rust.yml

Apart from this, I have also added a cargo fmt action, added cache support and fixed remaining clippy warnings.

CC: @giangndm: https://github.com/8xFF/atm0s-media-server/pull/349#issuecomment-2232288594

### Checklist

- [x] I have tested the changes locally.
- [x] I have reviewed the code changes.
- [x] I have updated the documentation, if necessary.

### CODE REVIEW

**Comment by dhilipsiva** [comment]
@giangndm Can you please delete the 94MB Cache from here? 

https://github.com/8xFF/atm0s-media-server/actions/caches

Duplicate cache got created because of workflow race condition

**Comment by giangndm** [comment]
@dhilipsiva I just clear all caches.

**Comment by dhilipsiva** [comment]
@giangndm Do you need me to make anymore changes on this?

**Review by giangndm — APPROVED** [review]
@dhilipsiva  I will merge it now.

**Pull request merged**
